version: "3.4"

services:
  postgresql:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: shivam
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  redis: