version: "3.9"

services:
  fastapi_postgres:
    image: postgres:16-alpine
    container_name: fastapi_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shivam
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: fastapi_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: shivam
      REDIS_PASSWORD: shivam2003
    command: [ "redis-server", "--requirepass", "shivam2003" ]

volumes:
  postgres_data:
  redis_data:
