version: "3.8"

services:
  postgresql:
    image: postgres:14.2-alpine
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: shivam
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.2.7
    container_name: fastapi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
