services:
  fastapi_postgres:
    image: postgres:16-alpine
    container_name: fastapi_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shivam
      POSTGRES_PASSWORD: shivam2003
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
